[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mlm-games/game-utils"
rust-version = "1.96"

[workspace.dependencies]
glam = "0.33.2"
serde = { version = "1", features = ["derive"] }
ron = "0.12"
directories = "6"
unic-langid = "0.9"
fluent-bundle = "0.16"
rand = "0.10"
bevy = { git = "https://github.com/bevyengine/bevy", rev = "fb89a8649d9b359e53ffb6e5492ebb7c059ac8af", default-features = false, features = [
    "bevy_asset",
    "bevy_audio",
    "bevy_camera",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_log",
    "bevy_render",
    "bevy_shader",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "reflect_auto_register",
] }
game-utils = { path = "crates/game-utils", version = "0.1.2" }
